name: Download Docker Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '镜像名称 (例如: node:20-bullseye)'
        required: true
        type: string
        default: 'node:20-bullseye'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.image_name }}
          
      - name: Save Docker image
        run: |
          SAFE_NAME=$(echo "${{ github.event.inputs.image_name }}" | tr '/:' '_')
          docker save ${{ github.event.inputs.image_name }} -o ${SAFE_NAME}.tar
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.image_name }}
          path: "*.tar"
